# Generated by Django 5.2.15 on 2026-07-06 11:02

import django.core.validators
import django.db.models.deletion
import workspaces.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
                                "Use lowercase letters, numbers and hyphens (no leading/trailing hyphen).",
                            ),
                            workspaces.validators.validate_not_reserved,
                        ],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("user", "User"), ("band", "Band")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "user"), ("user__isnull", False)),
                            models.Q(("kind", "band"), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="owner_kind_matches_link",
                    )
                ],
            },
        ),
    ]
